:heavy_minus_sign:　TOPのカルーセル消したよ
yuu-eguci/pari-yo-jana-924 pull request #16
Opened 2020-09-14 15:25 UTC by onsentawake

2020-09-15 14:53 UTC, yuu-eguci requested changes
## カルーセルについて

画像のとおり、勝手に動くことはなくなりましたが動かすことはできて、 JS エラーが発生しています。

![pr](https://user-images.githubusercontent.com/28250432/93225278-fe3bf800-f7ac-11ea-99e2-41fa3b990938.png)

## その他の追加ページについて

画像のとおりの、問題があります。

![pr2](https://user-images.githubusercontent.com/28250432/93225366-190e6c80-f7ad-11ea-94d2-c6e9c4d7d6a6.png)

## PR について

と、いうような問題は見受けられるんですが……ｗ
こんなのページを多数追加したら当然たくさん発生するものなので、それ自体は問題じゃないです。

だけれど「master は出来るだけ問題のない状態にしたい」という決まりがあるので、このままだといつまでたってもマージできないです……。

だから、「PR はできるだけ小さい単位で」というルールがあるんです。
次からよろしく！

今回は、ひとつめの、カルーセルが動かせてしまう問題だけ修正お願いしたいです。
むつかしいと思いますのでヒントを!

- `welcome-slides` についている `owl-carousel` が怪しいですね。消しましょう。
- `welcome-slides` に carousel 処理を施していそうなスクリプトが active.js に、ありますね。怪しい。消しましょう。

2020-09-15 14:53 UTC, yuu-eguci commented on index.html
> -        </div>
消さないでください!
また閉じタグが抜けてます!

おすすめ: VSCode の extension で、閉じタグが抜けているときアラートを出すやつがあるよーな気がします。

2020-09-22 04:43 UTC, onsentawake commented
一旦、カルーセルと閉じタグのみ修正

2020-09-22 05:30 UTC, yuu-eguci approved these changes
スマホ表示の index.html において、文字がヘッダーにかぶってしまっている問題が起こったりしておりますが……

![com](https://user-images.githubusercontent.com/28250432/93846785-08478480-fce0-11ea-87fd-13d4a6e77c6f.png)

OK です！この PR は、カルーセル修正完了ということでマージします！

2020-09-22 05:30 UTC, merged