#55 💄 ページタイトルの形式を統一
yuu-eguci/pari-yo-jana-924 pull request #57
Opened 2020-10-05 14:36 UTC by onsentawake

レビューとマージお願いしまーす！

本日はここまで

2020-10-05 15:19 UTC, yuu-eguci requested changes
ああ……なるほどｗ
ええ、勘違いです。

> `[ページ名] - Guitar Shop Neo` 全部こうする。

これは、「会社概要 - Guitar Shop Neo」「Sword Guitars - Guitar Shop Neo」のように、「ページ名 + サイト名」という形式に揃える、ということがいいたかったんです。

2020-10-06 00:17 UTC, onsentawake commented
アドバイスあざます～
修正しました、確認と合格ならマージおねがいします！

2020-10-06 00:18 UTC, yuu-eguci approved these changes
OK! ありがとうございます。
トップはそのままですね、りょーかいです!

2020-10-06 00:18 UTC, merged

2020-10-06 00:19 UTC, yuu-eguci commented
ちゃんと読んでいますよ〜!

![stack](https://user-images.githubusercontent.com/28250432/95144975-fc19f780-07b4-11eb-9c10-18d428d6bf0a.png)