Feature/#75 correction of text
yuu-eguci/pari-yo-jana-924 pull request #76
Opened 2021-01-27 14:43 UTC by onsentawake

Neoselect のページとSwordのページを924さんの文章をベースに書き換えました
確認とマージおねがいしますー！

また何か要望があったらおしえてくれるそうでーす

2021-01-27 23:42 UTC, yuu-eguci requested changes

2021-01-27 23:42 UTC, yuu-eguci commented on neoselect.html
> +                        <p>ギターが最も輝いていた時代をシュミレーションし、そのサウンドをごく小さなアンプでも再現できるようにピックアップ、POT、キャパシター、配線材など細かな部分の組み合わせが高いレベルで構築されております。</p>
シュミレーション -> `シミュレーション`

2021-01-27 23:57 UTC, onsentawake commented on neoselect.html
> +                        <p>ギターが最も輝いていた時代をシュミレーションし、そのサウンドをごく小さなアンプでも再現できるようにピックアップ、POT、キャパシター、配線材など細かな部分の組み合わせが高いレベルで構築されております。</p>
おおおおDNBD

2021-01-28 00:07 UTC, onsentawake commented on neoselect.html
> +                        <p>ギターが最も輝いていた時代をシュミレーションし、そのサウンドをごく小さなアンプでも再現できるようにピックアップ、POT、キャパシター、配線材など細かな部分の組み合わせが高いレベルで構築されております。</p>
修正しました!

2021-01-28 00:08 UTC, yuu-eguci approved these changes
修正 dnbd!
マージします。

2021-01-28 00:08 UTC, merged